version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: movie_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
      MYSQL_USER: dani
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
